# Generated by Django 4.2.7 on 2023-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_address', models.CharField(max_length=256)),
                ('occasion', models.CharField(choices=[('', 'Select an occasion'), ('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Graduation', 'Graduation'), ('Baby Shower', 'Baby Shower'), ('other', 'Other')], max_length=100)),
                ('other_occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('cake_size', models.CharField(choices=[('', 'Select a size'), ('6-inch (serves 8-10)', '6-inch (serves 8-10)'), ('8-inch (serves 12-15)', '8-inch (serves 12-15)'), ('10-inch (serves 20-25)', '10-inch (serves 20-25)'), ('Custom size', 'Custom size')], max_length=100)),
                ('cake_other_size', models.CharField(blank=True, max_length=100, null=True)),
                ('cake_shape', models.CharField(choices=[('', 'Select a shape'), ('Round', 'Round'), ('Square', 'Square'), ('Rectangle', 'Rectangle'), ('Heart', 'Heart'), ('Custom shape', 'Custom shape')], max_length=100)),
                ('cake_other_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('cake_flavors', models.CharField(choices=[('', 'Select flavors'), ('Buttercream', 'Vanilla'), ('Chocolate', 'Chocolate'), ('Red Velvet', 'Red Velvet'), ('Carrot', 'Carrot'), ('Marble', 'Marble'), ('Custom flavor', 'Custom flavor')], max_length=100)),
                ('cake_other_flavors', models.CharField(blank=True, max_length=100, null=True)),
                ('cake_filling', models.CharField(choices=[('', 'Select a Filling Type'), ('Buttercream', 'Buttercream'), ('Chocolate Ganache', 'Chocolate Ganache'), ('Fruit', 'Fruit'), ('Cream Cheese', 'Cream Cheese'), ('Custard', 'Custard'), ('other', 'Other')], max_length=100)),
                ('cake_other_filling', models.CharField(blank=True, max_length=100, null=True)),
                ('cake_frosting', models.CharField(choices=[('', 'Select a frosting'), ('Buttercream', 'Buttercream'), ('Fondant', 'Fondant'), ('Whipped Cream', 'Whipped Cream'), ('Chocolate', 'Chocolate'), ('Cream Cheese', 'Cream Cheese'), ('Naked (Minimal frosting)', 'Naked (Minimal frosting)')], max_length=100)),
                ('cake_decorations', models.CharField(choices=[('', 'Select a disoration'), ('Sprinkles', 'Sprinkles'), ('Edible Flowers', 'Edible Flowers'), ('Fondant Figures', 'Fondant Figures'), ('Chocolate Shavings', 'Chocolate Shavings'), ('Fresh Fruits', 'Fresh Fruits'), ('Edible Glitter', 'Edible Glitter'), ('Custom decoration', 'Custom decoration')], max_length=100)),
                ('cake_other_decorations', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(max_length=256)),
                ('font_style', models.CharField(max_length=256)),
                ('colour', models.CharField(max_length=256)),
                ('delivaery_or_pickme', models.CharField(choices=[('', 'Select a delivary type'), ('Delivery (extra charges may apply)', 'Delivery (extra charges may apply)'), ('Pickup', 'Pickup')], max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('paymentmethod', models.CharField(choices=[('', 'Select a payment method'), ('Cash', 'Cash'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Online Payment (e.g., PayPal)', 'Online Payment (e.g., PayPal)'), ('other', 'other')], max_length=100)),
                ('other_paymentmethod', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='media')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
