# Generated by Django 4.2.7 on 2023-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
