# Generated by Django 4.2.7 on 2023-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_form_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fruit_types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
