# Generated by Django 4.2.7 on 2023-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_fruit_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='additional_requests',
            field=models.TextField(default=0.0004943153732081067),
            preserve_default=False,
        ),
    ]
