# Generated by Django 4.2.7 on 2023-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_additional_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('', 'Select a payment method'), ('Cash', 'Cash'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Online Payment (e.g., PayPal)', 'Online Payment (e.g., PayPal)'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
