# Generated by Django 4.2.7 on 2023-11-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_form_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='cake_other_size',
            new_name='other_cake_size',
        ),
    ]
